apiVersion: apps/v1
kind: Deployment
metadata:
  name: springtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springtest
  template:
    metadata:
      labels:
        app: springtest
    spec:
      containers:
      - name: springtest
        image: nirmalbt/springtest:third
        ports:
        - containerPort: 8080
        env:
        - name: APP_CONFIG_KEY1
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: app.config.key2
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password

