apiVersion: v1
kind: Service
metadata:
  name: kafkaesque
  labels:
    app: kafkaesque
spec:
  selector:
    app: kafkaesque
  ports:
  - name: outside
    protocol: TCP
    port: 9092
    targetPort: 9092
    
  - name: inside
    protocol: TCP
    port: 9093
    targetPort: 9093
  type: NodePort
